mixed_Case="A Song of Ice and Fire"
print(mixed_Case.isupper())
print(mixed_Case.islower())
print(mixed_Case.upper())
print(mixed_Case.lower())
print(mixed_Case.istitle())
title_case=mixed_Case.title()
print(title_case)
print(mixed_Case.startswith("A"))
print(mixed_Case.endswith("e"))
words=mixed_Case.split()
print(words)